# Generated by Django 5.1.15 on 2026-09-29 12:11

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBenchmarkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('INGEST_CHUNK_PARSE', 'Document Chunk Parsing'), ('EMBEDDING_GEN', 'Dense Embedding Generation'), ('RRF_RETRIEVAL', 'Reciprocal Rank Fusion Retrieval'), ('LLM_SYNTHESIS', 'LLM Inference and Answer Synthesis'), ('CITATION_VERIFY', 'Citation Grounding Verification')], db_index=True, max_length=64)),
                ('model_name', models.CharField(default='system', max_length=128)),
                ('duration_ms', models.FloatField(help_text='Execution duration in milliseconds measured via time.perf_counter()')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Estimated dollar cost calculated per official rate tables', max_digits=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='SUCCESS', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_auditbenchmarklog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'status'], name='analytics_a_operati_f95c0b_idx'), models.Index(fields=['created_at'], name='analytics_a_created_d51769_idx')],
            },
        ),
    ]
