# Generated by Django 5.1.15 on 2026-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditbenchmarklog',
            name='operation',
            field=models.CharField(choices=[('INGEST_CHUNK_PARSE', 'Document Chunk Parsing'), ('EMBEDDING_GEN', 'Dense Embedding Generation'), ('RRF_RETRIEVAL', 'Reciprocal Rank Fusion Retrieval'), ('LLM_SYNTHESIS', 'LLM Inference and Answer Synthesis'), ('CITATION_VERIFY', 'Citation Grounding Verification'), ('AUTH_VERIFY', 'Authentication Verification')], db_index=True, max_length=64),
        ),
    ]
