# Generated by Django 5.1.15 on 2026-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_auditbenchmarklog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditbenchmarklog',
            name='operation',
            field=models.CharField(choices=[('INGEST_CHUNK_PARSE', 'Document Chunk Parsing'), ('EMBEDDING_GEN', 'Dense Embedding Generation'), ('RRF_RETRIEVAL', 'Reciprocal Rank Fusion Retrieval'), ('LLM_SYNTHESIS', 'LLM Inference and Answer Synthesis'), ('CITATION_VERIFY', 'Citation Grounding Verification'), ('AUTH_VERIFY', 'Authentication Verification'), ('REDUCE_SYNTHESIS', 'Reduce-Stage Frontier Synthesis'), ('FAST_PATH_SYNTHESIS', 'Fast-Path Extractive Synthesis'), ('MULTI_DOC_QUERY', 'Multi-Document Query Execution'), ('AB_BENCHMARK', 'A/B Benchmark Query Execution')], db_index=True, max_length=64),
        ),
    ]
